### ISSUE TITLE
Using `current_app.default_config`

### ISSUE THREAD

**Issue by bsandrow** [trendmicro/flask-ini#4]
I'm interested in this module, but I'm not quite sure about [this section](https://github.com/trendmicro/flask-ini/blob/master/flask_ini.py#L38-L58):

```python
    def _load_item(self, key):
        '''Load the specified item from the [flask] section. Type is
        determined by the type of the equivalent value in app.default_config
        or string if unknown.'''
        key_u   = key.upper()
        default = current_app.default_config.get(key_u)

        # One of the default config vars is a timedelta - interpret it
        # as an int and construct using it
        if isinstance(default, datetime.timedelta):
            current_app.config[key_u] = datetime.timedelta(self.getint('flask', key))
        elif isinstance(default, bool):
            current_app.config[key_u] = self.getboolean('flask', key)
        elif isinstance(default, float):
            current_app.config[key_u] = self.getfloat('flask', key)
        elif isinstance(default, int):
            current_app.config[key_u] = self.getint('flask', key)
        else:
            # All the string keys need to be coerced into str()
            # because Flask expects some of them not to be unicode
            current_app.config[key_u] = str(self.get('flask', key))
```

 You're relying on `current_app.default_config` to determine the type of the config option, but `default_config` is defined by Flask [here](https://github.com/mitsuhiko/flask/blob/aaebe9fe252454a319de1f0e583d0e5a8635e399/flask/app.py#L276-L304):

```python
    #: Default configuration parameters.
    default_config = ImmutableDict({
        'DEBUG':                                False,
        'TESTING':                              False,
        'PROPAGATE_EXCEPTIONS':                 None,
        'PRESERVE_CONTEXT_ON_EXCEPTION':        None,
        'SECRET_KEY':                           None,
        'PERMANENT_SESSION_LIFETIME':           timedelta(days=31),
        'USE_X_SENDFILE':                       False,
        'LOGGER_NAME':                          None,
        'LOGGER_HANDLER_POLICY':               'always',
        'SERVER_NAME':                          None,
        'APPLICATION_ROOT':                     None,
        'SESSION_COOKIE_NAME':                  'session',
        'SESSION_COOKIE_DOMAIN':                None,
        'SESSION_COOKIE_PATH':                  None,
        'SESSION_COOKIE_HTTPONLY':              True,
        'SESSION_COOKIE_SECURE':                False,
        'SESSION_REFRESH_EACH_REQUEST':         True,
        'MAX_CONTENT_LENGTH':                   None,
        'SEND_FILE_MAX_AGE_DEFAULT':            12 * 60 * 60,  # 12 hours
        'TRAP_BAD_REQUEST_ERRORS':              False,
        'TRAP_HTTP_EXCEPTIONS':                 False,
        'EXPLAIN_TEMPLATE_LOADING':             False,
        'PREFERRED_URL_SCHEME':                 'http',
        'JSON_AS_ASCII':                        True,
        'JSON_SORT_KEYS':                       True,
        'JSONIFY_PRETTYPRINT_REGULAR':          True,
        'TEMPLATES_AUTO_RELOAD':                None,
    })
```

If you have any user-defined options beyond the default `Flask` options, the user it forced to treat them as strings. Are you intending users of `flask-ini` to extend `current_app.default_config` to include all of their default options? Flask has [this advice](https://github.com/mitsuhiko/flask/blob/aaebe9fe252454a319de1f0e583d0e5a8635e399/flask/config.py#L146-L158) on default config options:

```
        Objects are usually either modules or classes.
        Just the uppercase variables in that object are stored in the config.
        Example usage::
            app.config.from_object('yourapplication.default_config')
            from yourapplication import default_config
            app.config.from_object(default_config)
        You should not use this function to load the actual configuration but
        rather configuration defaults.  The actual config should be loaded
        with :meth:`from_pyfile` and ideally from a location not within the
        package because the package might be installed system wide.
```

It would seem that a better approach would be to either get a reference to a user-defined `default_config` object/dict, or to have a dict that defines the type of specific options.

**Comment by bsandrow** [comment]
I guess that I should note, one of the biggest use-cases here would be in having integer and boolean options. It's possible that you could pattern-match to cast those types as well.

**Comment by pedantic-git** [comment]
Hi Brandon

My intention with this module is to allow a complete ini-file divided into sections to be used as the config file for a Flask application. My thought here was that all user-defined options would go into user-defined sections and the `[flask]` section was reserved for options that Flask reserves for itself.

For example, in the [README](README.md) there's a `[backend]` section.

However, you're right that this will cause problems with any third-party modules that expect their own variables to be defined in the Flask config. Any patches (with appropriate test cases) to support custom overrides to the `default_config` would be very welcome as pull requests!

**Comment by bsandrow** [comment]
I'll go back and read the docs more closely. My impression on reading them was that Flask-INI was *only* loading from the `[flask]` section, and that those other sections were possibly for other things (e.g. multiple applications -- not necessarily web applications -- might share the same `production.ini` file). Thanks for the reply.

**Comment by pedantic-git** [comment]
OK - it's good to know someone might have interpreted the docs that way. If you can see any way the docs can be improved, please let me know.

You can certainly use Flask-ini to share a config file between multiple pieces of an application, and that's one of its primary use cases. But in the Flask-ini world the intention is that all your config is in structured sections, not just the non-Flask stuff.

**Comment by pedantic-git** [comment]
Closing this issue for now but please reopen if you have suggestions for improvement.
